package model;
// Generated 12/11/2014 11:53:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import model.persistencia.DAOCaixa;

/**
 * Caixa generated by hbm2java
 */
public class Caixa  implements java.io.Serializable {


     private Integer idCaixa;
     private Usuario usuario;
     private Date dataAbertura;
     private Date dataFechamento;
     private BigDecimal valorInicial;
     private Set caixasangrias = new HashSet(0);
     private Set vendas = new HashSet(0);
     private Set caixasuprimentos = new HashSet(0);

    public Caixa() {
    }

	
    public Caixa(Usuario usuario, Date dataAbertura, Date dataFechamento, BigDecimal valorInicial) {
        this.usuario = usuario;
        this.dataAbertura = dataAbertura;
        this.dataFechamento = dataFechamento;
        this.valorInicial = valorInicial;
    }
    public Caixa(Usuario usuario, Date dataAbertura, Date dataFechamento, BigDecimal valorInicial, Set caixasangrias, Set vendas, Set caixasuprimentos) {
       this.usuario = usuario;
       this.dataAbertura = dataAbertura;
       this.dataFechamento = dataFechamento;
       this.valorInicial = valorInicial;
       this.caixasangrias = caixasangrias;
       this.vendas = vendas;
       this.caixasuprimentos = caixasuprimentos;
    }
   
    public Integer getIdCaixa() {
        return this.idCaixa;
    }
    
    public void setIdCaixa(Integer idCaixa) {
        this.idCaixa = idCaixa;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getDataAbertura() {
        return this.dataAbertura;
    }
    
    public void setDataAbertura(Date dataAbertura) {
        this.dataAbertura = dataAbertura;
    }
    public Date getDataFechamento() {
        return this.dataFechamento;
    }
    
    public void setDataFechamento(Date dataFechamento) {
        this.dataFechamento = dataFechamento;
    }
    public BigDecimal getValorInicial() {
        return this.valorInicial;
    }
    
    public void setValorInicial(BigDecimal valorInicial) {
        this.valorInicial = valorInicial;
    }
    public Set getCaixasangrias() {
        return this.caixasangrias;
    }
    
    public void setCaixasangrias(Set caixasangrias) {
        this.caixasangrias = caixasangrias;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }
    public Set getCaixasuprimentos() {
        return this.caixasuprimentos;
    }
    
    public void setCaixasuprimentos(Set caixasuprimentos) {
        this.caixasuprimentos = caixasuprimentos;
    }

}


