package model;
// Generated 12/11/2014 11:53:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Caixasuprimento generated by hbm2java
 */
public class Caixasuprimento  implements java.io.Serializable {


     private Integer idCaixaSuprimento;
     private Caixa caixaaberturafechamento;
     private Usuario usuario;
     private BigDecimal valorAdicionado;
     private Date data;

    public Caixasuprimento() {
    }

    public Caixasuprimento(Caixa caixaaberturafechamento, Usuario usuario, BigDecimal valorAdicionado, Date data) {
       this.caixaaberturafechamento = caixaaberturafechamento;
       this.usuario = usuario;
       this.valorAdicionado = valorAdicionado;
       this.data = data;
    }
   
    public Integer getIdCaixaSuprimento() {
        return this.idCaixaSuprimento;
    }
    
    public void setIdCaixaSuprimento(Integer idCaixaSuprimento) {
        this.idCaixaSuprimento = idCaixaSuprimento;
    }
    public Caixa getCaixaaberturafechamento() {
        return this.caixaaberturafechamento;
    }
    
    public void setCaixaaberturafechamento(Caixa caixaaberturafechamento) {
        this.caixaaberturafechamento = caixaaberturafechamento;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getValorAdicionado() {
        return this.valorAdicionado;
    }
    
    public void setValorAdicionado(BigDecimal valorAdicionado) {
        this.valorAdicionado = valorAdicionado;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


