package model;
// Generated 12/11/2014 11:53:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Colaborador generated by hbm2java
 */
public class Colaborador  implements java.io.Serializable {


     private Integer idColaborador;
     private Cargo cargo;
     private String cpf;
     private String nome;
     private Set usuarios = new HashSet(0);

    public Colaborador() {
    }

	
    public Colaborador(Cargo cargo, String cpf, String nome) {
        this.cargo = cargo;
        this.cpf = cpf;
        this.nome = nome;
    }
    public Colaborador(Cargo cargo, String cpf, String nome, Set usuarios) {
       this.cargo = cargo;
       this.cpf = cpf;
       this.nome = nome;
       this.usuarios = usuarios;
    }
   
    public Integer getIdColaborador() {
        return this.idColaborador;
    }
    
    public void setIdColaborador(Integer idColaborador) {
        this.idColaborador = idColaborador;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


