package model;
// Generated 05/12/2014 19:18:02 by Hibernate Tools 4.3.1



/**
 * Feature generated by hbm2java
 */
public class Feature  implements java.io.Serializable {


     private Integer idFeature;
     private String descricao;
     private char status;

    public Feature() {
    }

    public Feature(String descricao, char status) {
       this.descricao = descricao;
       this.status = status;
    }
   
    public Integer getIdFeature() {
        return this.idFeature;
    }
    
    public void setIdFeature(Integer idFeature) {
        this.idFeature = idFeature;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }




}


