package model;
// Generated 05/12/2014 19:18:02 by Hibernate Tools 4.3.1



/**
 * Feature generated by hbm2java
 */
public class Feature  implements java.io.Serializable {


     private Integer idFeature;
     private String descricao;
     private char status;
     private boolean ativa;
     private String statusString;

    public Feature() {
    }

    public Feature(String descricao, char status) {
       this.descricao = descricao;
       this.status = status;
    }
   
    public Integer getIdFeature() {
        return this.idFeature;
    }
    
    public void setIdFeature(Integer idFeature) {
        this.idFeature = idFeature;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
        if(status=='A')
           this.ativa = true;
       else
           this.ativa = false;
       this.setStatusString();
    }

    /**
     * @return the ativa
     */
    public boolean isAtiva() {
        return ativa;
    }

    /**
     * @param ativa the ativa to set
     */
    public void setAtiva(boolean ativa) {        
        this.ativa = ativa;
    }

    /**
     * @return the statusString
     */
    public String getStatusString() {
        return statusString;
    }

    /**
     * @param statusString the statusString to set
     */
    public void setStatusString() {
        if (this.status == 'A')
            this.statusString="Ativa";
        else
            this.statusString="Inativa";
    }
}


