package model;
// Generated 12/11/2014 11:53:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Pagamentovenda generated by hbm2java
 */
public class Pagamentovenda  implements java.io.Serializable {


     private Integer idPagamentoVenda;
     private Tipopagamento tipopagamento;
     private Venda venda;
     private BigDecimal valor;
     private Integer numeroParcelas;

    public Pagamentovenda() {
    }

	
    public Pagamentovenda(Tipopagamento tipopagamento, Venda venda, BigDecimal valor) {
        this.tipopagamento = tipopagamento;
        this.venda = venda;
        this.valor = valor;
    }
    public Pagamentovenda(Tipopagamento tipopagamento, Venda venda, BigDecimal valor, Integer numeroParcelas) {
       this.tipopagamento = tipopagamento;
       this.venda = venda;
       this.valor = valor;
       this.numeroParcelas = numeroParcelas;
    }
   
    public Integer getIdPagamentoVenda() {
        return this.idPagamentoVenda;
    }
    
    public void setIdPagamentoVenda(Integer idPagamentoVenda) {
        this.idPagamentoVenda = idPagamentoVenda;
    }
    public Tipopagamento getTipopagamento() {
        return this.tipopagamento;
    }
    
    public void setTipopagamento(Tipopagamento tipopagamento) {
        this.tipopagamento = tipopagamento;
    }
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Integer getNumeroParcelas() {
        return this.numeroParcelas;
    }
    
    public void setNumeroParcelas(Integer numeroParcelas) {
        this.numeroParcelas = numeroParcelas;
    }




}


