package model;
// Generated 12/11/2014 11:53:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import model.persistencia.DAOVenda;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer idProduto;
     private Unidade unidade;
     private String descricao;
     private BigDecimal valorCusto;
     private BigDecimal valorVenda;
     private Integer quantidade;
     private Set produtogrades = new HashSet(0);
     private Set vendaitems = new HashSet(0);

    public Produto() {
    }

	
    public Produto(Unidade unidade, String descricao, BigDecimal valorCusto, BigDecimal valorVenda) {
        this.unidade = unidade;
        this.descricao = descricao;
        this.valorCusto = valorCusto;
        this.valorVenda = valorVenda;
    }
    public Produto(Unidade unidade, String descricao, BigDecimal valorCusto, BigDecimal valorVenda, Set produtogrades, Set vendaitems) {
       this.unidade = unidade;
       this.descricao = descricao;
       this.valorCusto = valorCusto;
       this.valorVenda = valorVenda;
       this.produtogrades = produtogrades;
       this.vendaitems = vendaitems;
    }
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getValorCusto() {
        return this.valorCusto;
    }
    
    public void setValorCusto(BigDecimal valorCusto) {
        this.valorCusto = valorCusto;
    }
    public BigDecimal getValorVenda() {
        return this.valorVenda;
    }
    
    public void setValorVenda(BigDecimal valorVenda) {
        this.valorVenda = valorVenda;
    }

    public Integer getQuantidade() {
        return quantidade;
    }

    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    
    public Set getProdutogrades() {
        return this.produtogrades;
    }
    
    public void setProdutogrades(Set produtogrades) {
        this.produtogrades = produtogrades;
    }
    public Set getVendaitems() {
        return this.vendaitems;
    }
    
    public void setVendaitems(Set vendaitems) {
        this.vendaitems = vendaitems;
    }
    public Produto search(Produto p) {
        return new DAOVenda().search(p);
    }





}


