package model;
// Generated 12/11/2014 11:53:29 by Hibernate Tools 4.3.1



/**
 * Produtograde generated by hbm2java
 */
public class Produtograde  implements java.io.Serializable {


     private Integer idProdutoGrade;
     private Cor cor;
     private Produto produto;
     private Tamanho tamanho;

    public Produtograde() {
    }

    public Produtograde(Cor cor, Produto produto, Tamanho tamanho) {
       this.cor = cor;
       this.produto = produto;
       this.tamanho = tamanho;
    }
   
    public Integer getIdProdutoGrade() {
        return this.idProdutoGrade;
    }
    
    public void setIdProdutoGrade(Integer idProdutoGrade) {
        this.idProdutoGrade = idProdutoGrade;
    }
    public Cor getCor() {
        return this.cor;
    }
    
    public void setCor(Cor cor) {
        this.cor = cor;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Tamanho getTamanho() {
        return this.tamanho;
    }
    
    public void setTamanho(Tamanho tamanho) {
        this.tamanho = tamanho;
    }




}


