package model;
// Generated 12/11/2014 11:53:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tamanho generated by hbm2java
 */
public class Tamanho  implements java.io.Serializable {


     private Integer idTamanho;
     private String descricao;
     private Set produtogrades = new HashSet(0);

    public Tamanho() {
    }

	
    public Tamanho(String descricao) {
        this.descricao = descricao;
    }
    public Tamanho(String descricao, Set produtogrades) {
       this.descricao = descricao;
       this.produtogrades = produtogrades;
    }
   
    public Integer getIdTamanho() {
        return this.idTamanho;
    }
    
    public void setIdTamanho(Integer idTamanho) {
        this.idTamanho = idTamanho;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getProdutogrades() {
        return this.produtogrades;
    }
    
    public void setProdutogrades(Set produtogrades) {
        this.produtogrades = produtogrades;
    }




}


