package model;
// Generated 12/11/2014 11:53:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopagamento generated by hbm2java
 */
public class Tipopagamento  implements java.io.Serializable {


     private Integer idTipoPagamento;
     private String descricao;
     private Set pagamentovendas = new HashSet(0);

    public Tipopagamento() {
    }

	
    public Tipopagamento(String descricao) {
        this.descricao = descricao;
    }
    public Tipopagamento(String descricao, Set pagamentovendas) {
       this.descricao = descricao;
       this.pagamentovendas = pagamentovendas;
    }
   
    public Integer getIdTipoPagamento() {
        return this.idTipoPagamento;
    }
    
    public void setIdTipoPagamento(Integer idTipoPagamento) {
        this.idTipoPagamento = idTipoPagamento;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getPagamentovendas() {
        return this.pagamentovendas;
    }
    
    public void setPagamentovendas(Set pagamentovendas) {
        this.pagamentovendas = pagamentovendas;
    }




}


