package model;
// Generated 12/11/2014 11:53:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Unidade generated by hbm2java
 */
public class Unidade  implements java.io.Serializable {


     private Integer idUnidade;
     private String descricao;
     private Set produtos = new HashSet(0);

    public Unidade() {
    }

	
    public Unidade(String descricao) {
        this.descricao = descricao;
    }
    public Unidade(String descricao, Set produtos) {
       this.descricao = descricao;
       this.produtos = produtos;
    }
   
    public Integer getIdUnidade() {
        return this.idUnidade;
    }
    
    public void setIdUnidade(Integer idUnidade) {
        this.idUnidade = idUnidade;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


